plugins {
    id 'fabric-loom' version '1.14'
    id 'java'
}

base {
    archivesName = 'QuickShulkerForStarCity-client'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.11'
    loom.officialMojangMappings()
    modImplementation 'net.fabricmc:fabric-loader:0.18.1'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.141.3+1.21.11'
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    // 确保生成的字节码兼容Java 21
    options.compilerArgs += ['--release', '21']
}

jar {
    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}
