plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'java'
}

base {
    archivesName = 'QuickShulkerForStarCity-client'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.4'
    mappings 'net.fabricmc:yarn:1.21.4+build.8:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.16.9'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.110.5+1.21.4'
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    // 确保生成的字节码兼容Java 21
    options.compilerArgs += ['--release', '21']
}

jar {
    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}
