plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    // 确保生成的字节码兼容Java 21
    options.compilerArgs += ['--release', '21']
}

processResources {
    filesMatching('plugin.yml') {
        expand(
            'version': project.version
        )
    }
}

jar {
    archiveBaseName = 'QuickShulkerForStarCity-server'
    archiveVersion = project.version
}
